apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: baremetal-operator-system

resources:
  - namespace.yaml
  - ironic-configmap.yaml
  - ironic-deployment.yaml
  - baremetal-operator.yaml

# Use remote base from official Metal3 repo for CRDs
# This ensures we get the latest BareMetalHost CRD
