---
# ReferenceGrant allows the Gateway in ingress namespace
# to reference the TLS certificate Secret in tink-system namespace
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-tls
  namespace: tink-system
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ingress
  to:
    - group: ""
      kind: Secret
      name: tinkerbell-tls
