apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - blackbox-exporter.yaml
  - loki.yaml
  - tempo.yaml
  - jaeger.yaml
  - tinkerbell-service-monitors.yaml
  - tinkerbell-alerting-rules.yaml
  - promtail-daemonset.yaml
  - promtail-config.yaml
  - grafana-dashboards.yaml
  - network-monitoring.yaml
  - bare-metal-health.yaml
